(()=>{'use strict';
const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),spark=document.getElementById('sparkCanvas'),sctx=spark.getContext('2d'),$=id=>document.getElementById(id);
const C={ink:'#102d46',road:'#b9ced8',white:'#f8fbfa',amber:'#f4ba47',coral:'#ef6c51',mint:'#5aaf96',blue:'#2785a9'};
const nodes=[{x:.10,y:.27,label:'Harbor'},{x:.34,y:.10,label:'North'},{x:.68,y:.13,label:'Market'},{x:.88,y:.36,label:'East'},{x:.73,y:.76,label:'Park'},{x:.37,y:.83,label:'Station'},{x:.15,y:.61,label:'West'}];
const road=(a,b,name,curve,base=1)=>({a,b,name,curve,lanes:1,base,traffic:0,selected:false,flash:0});
const roads=[road(0,1,'Harbor Bend',-.10,1.05),road(1,2,'North Avenue',.02,.92),road(2,3,'Market Link',-.04,.94),road(3,4,'Garden Curve',-.12,1.08),road(4,5,'Parkway',.03,.92),road(5,6,'Station Road',-.06,.93),road(6,0,'West Arc',-.10,1),road(1,5,'Civic Cut',.09,.78),road(2,6,'Sunline',-.04,.72)];
const state={w:0,h:0,dpr:1,elapsed:0,duration:90,spawnClock:0,paused:false,sound:true,ended:false,selected:2,cars:[],completed:0,budget:720,averageTime:12.4,networkFlow:100,history:[12.4],nextSample:0,lastFrame:performance.now()};roads[2].selected=true;
function resize(){const r=canvas.getBoundingClientRect();state.dpr=Math.min(devicePixelRatio||1,2);state.w=r.width;state.h=r.height;canvas.width=Math.round(r.width*state.dpr);canvas.height=Math.round(r.height*state.dpr);const sr=spark.getBoundingClientRect();spark.width=Math.round(sr.width*state.dpr);spark.height=Math.round(sr.height*state.dpr)}
function nodePoint(i){const n=nodes[i],wide=state.w>700,pad=wide?Math.min(170,state.w*.12):22,top=wide?6:46,bottom=wide?8:76;return{x:pad+n.x*(state.w-pad*2),y:top+n.y*(state.h-top-bottom)}}
function geometry(r){const p0=nodePoint(r.a),p2=nodePoint(r.b),dx=p2.x-p0.x,dy=p2.y-p0.y,len=Math.hypot(dx,dy);return{p0,p2,p1:{x:(p0.x+p2.x)/2-dy/len*r.curve*len,y:(p0.y+p2.y)/2+dx/len*r.curve*len}}}
function bez(g,t){const q=1-t;return{x:q*q*g.p0.x+2*q*t*g.p1.x+t*t*g.p2.x,y:q*q*g.p0.y+2*q*t*g.p1.y+t*t*g.p2.y}}
function tangent(g,t){return{x:2*(1-t)*(g.p1.x-g.p0.x)+2*t*(g.p2.x-g.p1.x),y:2*(1-t)*(g.p1.y-g.p0.y)+2*t*(g.p2.y-g.p1.y)}}
function strokeRoad(r){const g=geometry(r),width=17+r.lanes*5;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';const path=()=>{ctx.beginPath();ctx.moveTo(g.p0.x,g.p0.y);ctx.quadraticCurveTo(g.p1.x,g.p1.y,g.p2.x,g.p2.y)};path();ctx.lineWidth=width+7;ctx.strokeStyle=C.ink;ctx.stroke();path();ctx.lineWidth=width;ctx.strokeStyle=r.selected?'#f5c65f':C.road;ctx.stroke();path();ctx.lineWidth=Math.max(4,width-10);ctx.strokeStyle=r.selected?'rgba(255,226,143,.52)':'rgba(222,234,237,.68)';ctx.stroke();path();ctx.lineWidth=1.8;ctx.strokeStyle='rgba(255,255,255,.9)';ctx.setLineDash([7,9]);ctx.stroke();if(r.selected){path();ctx.setLineDash([]);ctx.lineWidth=2;ctx.strokeStyle='rgba(220,143,45,.85)';ctx.stroke()}if(r.flash>0){path();ctx.setLineDash([]);ctx.lineWidth=width+13+r.flash*4;ctx.strokeStyle=`rgba(244,186,71,${r.flash*.22})`;ctx.stroke()}ctx.restore()}
function drawNodes(){nodes.forEach((n,i)=>{const p=nodePoint(i),busy=roads.filter(r=>r.a===i||r.b===i).reduce((s,r)=>s+r.traffic,0);ctx.save();ctx.beginPath();ctx.arc(p.x,p.y,12.5,0,Math.PI*2);ctx.fillStyle=C.white;ctx.fill();ctx.lineWidth=3;ctx.strokeStyle=C.ink;ctx.stroke();ctx.beginPath();ctx.arc(p.x,p.y,4.3,0,Math.PI*2);ctx.fillStyle=busy>11?C.coral:busy>6?C.amber:C.blue;ctx.fill();ctx.restore()})}
function drawCars(){state.cars.forEach(car=>{const r=roads[car.road],g=geometry(r),t=car.direction>0?car.t:1-car.t,p=bez(g,t),tan=tangent(g,t),angle=Math.atan2(tan.y,tan.x)+(car.direction>0?0:Math.PI),offset=((car.slot%Math.max(1,r.lanes))-(r.lanes-1)/2)*4.2;ctx.save();ctx.translate(p.x-Math.sin(angle)*offset,p.y+Math.cos(angle)*offset);ctx.rotate(angle);ctx.beginPath();ctx.roundRect(-4.5,-2.5,9,5,2.5);ctx.fillStyle=car.color;ctx.fill();ctx.lineWidth=1;ctx.strokeStyle='rgba(16,45,70,.45)';ctx.stroke();ctx.restore()})}
function drawLabels(){if(state.w<520)return;nodes.forEach((n,i)=>{const p=nodePoint(i);ctx.save();ctx.fillStyle='rgba(16,45,70,.6)';ctx.font='800 8px Inter, sans-serif';ctx.textAlign='center';ctx.fillText(n.label.toUpperCase(),p.x,p.y+26);ctx.restore()})}
function drawProgress(){const x=25,y=state.h-20,w=Math.min(130,state.w*.24);ctx.save();ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w,y);ctx.strokeStyle='rgba(16,45,70,.12)';ctx.lineWidth=4;ctx.stroke();ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w*Math.min(1,state.elapsed/state.duration),y);ctx.strokeStyle=C.blue;ctx.stroke();ctx.fillStyle=C.ink;ctx.font='800 8px Inter, sans-serif';ctx.fillText(`${Math.max(0,Math.ceil(state.duration-state.elapsed))} SEC`,x,y-8);ctx.restore()}
function render(){ctx.setTransform(state.dpr,0,0,state.dpr,0,0);ctx.clearRect(0,0,state.w,state.h);roads.forEach(strokeRoad);drawCars();drawNodes();drawLabels();drawProgress()}
const capacity=r=>4+r.lanes*5,congestion=r=>Math.max(.35,r.traffic/capacity(r)),edgeCost=i=>{const r=roads[i],c=congestion(r);return r.base*(1+Math.pow(c,2.2)*2.4)/Math.sqrt(r.lanes)};
function route(start,end){const dist=nodes.map(()=>Infinity),prev=nodes.map(()=>null),open=new Set(nodes.map((_,i)=>i));dist[start]=0;while(open.size){let u=[...open].reduce((best,n)=>dist[n]<dist[best]?n:best);open.delete(u);if(u===end||!isFinite(dist[u]))break;roads.forEach((r,ri)=>{if(r.a!==u&&r.b!==u)return;const v=r.a===u?r.b:r.a;if(!open.has(v))return;const alt=dist[u]+edgeCost(ri);if(alt<dist[v]){dist[v]=alt;prev[v]={node:u,road:ri}}})}const path=[];let cur=end;while(cur!==start&&prev[cur]){path.unshift({road:prev[cur].road,from:prev[cur].node,to:cur});cur=prev[cur].node}return path.length?path:null}
function spawnCar(){const start=Math.floor(Math.random()*nodes.length);let end=Math.floor(Math.random()*nodes.length);while(end===start)end=Math.floor(Math.random()*nodes.length);const path=route(start,end);if(!path)return;const palette=['#ec7358','#2c88aa','#f3c44f','#5caf96','#f5f7f3'],first=path[0];state.cars.push({path,step:0,road:first.road,direction:roads[first.road].a===first.from?1:-1,t:0,total:0,slot:Math.floor(Math.random()*3),color:palette[Math.floor(Math.random()*palette.length)]});roads[first.road].traffic++}
function updateCars(dt){for(let i=state.cars.length-1;i>=0;i--){const car=state.cars[i],r=roads[car.road],slow=1+Math.pow(congestion(r),2.4)*2.8;car.t+=dt*(.25/r.base)/slow;car.total+=dt*slow;if(car.t<1)continue;r.traffic=Math.max(0,r.traffic-1);car.step++;if(car.step>=car.path.length){state.completed++;state.averageTime=state.averageTime*.92+Math.min(38,car.total*2.4)*.08;state.budget+=8;state.cars.splice(i,1);continue}const leg=car.path[car.step];car.road=leg.road;car.direction=roads[leg.road].a===leg.from?1:-1;car.t=0;roads[leg.road].traffic++}}
function update(dt){if(state.paused||state.ended)return;state.elapsed+=dt;state.spawnClock-=dt;const demand=.62-Math.min(.28,state.elapsed/state.duration*.28);if(state.spawnClock<=0){spawnCar();state.spawnClock=demand*(.75+Math.random()*.55)}updateCars(dt);roads.forEach(r=>r.flash=Math.max(0,r.flash-dt*1.7));const loads=roads.map(congestion),worst=Math.max(...loads),weighted=roads.reduce((sum,r)=>sum+r.traffic*Math.min(3.2,congestion(r)),0)/Math.max(1,state.cars.length),target=8.8+weighted*5.5+worst*2.1;state.averageTime+=(target-state.averageTime)*Math.min(1,dt*.55);state.networkFlow=Math.max(12,Math.min(100,108-weighted*26-worst*9));if(state.elapsed>=state.nextSample){state.history.push(state.averageTime);if(state.history.length>80)state.history.shift();state.nextSample=state.elapsed+1}if(state.elapsed>=state.duration)finish()}
function drawSpark(){const w=spark.width/state.dpr,h=spark.height/state.dpr,v=state.history,min=7,max=30;sctx.setTransform(state.dpr,0,0,state.dpr,0,0);sctx.clearRect(0,0,w,h);sctx.beginPath();v.forEach((n,i)=>{const x=8+i/79*(w-20),y=h-8-(Math.min(max,Math.max(min,n))-min)/(max-min)*(h-17);i?sctx.lineTo(x,y):sctx.moveTo(x,y)});sctx.lineWidth=2;sctx.lineCap='round';sctx.strokeStyle=state.averageTime>18?C.coral:C.blue;sctx.stroke();const last=v.at(-1),x=8+(v.length-1)/79*(w-20),y=h-8-(Math.min(max,Math.max(min,last))-min)/(max-min)*(h-17);sctx.beginPath();sctx.arc(x,y,3.5,0,Math.PI*2);sctx.fillStyle=state.averageTime>18?C.coral:C.amber;sctx.fill();sctx.beginPath();sctx.moveTo(8,h-8-(18-min)/(max-min)*(h-17));sctx.lineTo(w-8,h-8-(18-min)/(max-min)*(h-17));sctx.setLineDash([2,5]);sctx.strokeStyle='rgba(16,45,70,.14)';sctx.stroke();sctx.setLineDash([])}
function updateHUD(){const hot=roads.reduce((a,b)=>congestion(a)>congestion(b)?a:b),r=roads[state.selected],load=congestion(r);$('tripTime').innerHTML=`${state.averageTime.toFixed(1)} <small>min</small>`;$('networkFlow').innerHTML=`${Math.round(state.networkFlow)}<small>%</small>`;$('tripsDone').textContent=state.completed;$('budget').textContent=`$${state.budget}`;$('hotRoad').textContent=hot.name;$('hotRoadDetail').textContent=`${hot.lanes} LANE${hot.lanes>1?'S':''} · ${Math.round(congestion(hot)*100)}% LOAD`;const delta=state.history.length>5?state.averageTime-state.history[Math.max(0,state.history.length-5)]:0;$('trendLabel').textContent=delta>.6?'RISING':delta<-.6?'IMPROVING':'STABLE';$('trendLabel').style.color=delta>.6?C.coral:delta<-.6?C.mint:C.blue;$('roadName').textContent=r.name;$('laneCount').textContent=r.lanes;$('trafficCount').textContent=r.traffic;$('roadTravel').textContent=`${(r.base*(1+load*load*2.4)*3.2).toFixed(1)}m`;const pct=Math.min(100,Math.round(load*100));$('roadMeter').style.width=`${pct}%`;$('roadMeter').style.background=load>1.2?C.coral:load>.75?C.amber:C.mint;const status=load>1.2?'JAMMED':load>.75?'BUSY':'FLOWING',pill=$('flowPill');pill.textContent=status;pill.className=`flow-pill ${status==='JAMMED'?'jammed':status==='BUSY'?'slow':''}`;const cost=240+r.lanes*160;$('upgradeCost').textContent=`$${cost}`;$('upgradeButton').disabled=r.lanes>=3||state.budget<cost||state.ended;$('upgradeButton').querySelector('span').textContent=r.lanes>=3?'MAXIMUM WIDTH':'ADD A LANE';drawSpark()}
function hitRoad(x,y){let best=-1,dist=Infinity;roads.forEach((r,i)=>{const g=geometry(r);for(let s=0;s<=30;s++){const p=bez(g,s/30),d=Math.hypot(p.x-x,p.y-y);if(d<dist){dist=d;best=i}}});return dist<32?best:-1}
let audio=null,toastTimer;function tone(freq,duration){if(!state.sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext);const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch(e){}}
function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1600)}
function select(x,y){const i=hitRoad(x,y);if(i<0)return;roads.forEach(r=>r.selected=false);roads[i].selected=true;state.selected=i;$('hint').style.opacity='0';updateHUD();tone(420,.035)}
function upgrade(){const r=roads[state.selected],cost=240+r.lanes*160;if(r.lanes>=3||state.budget<cost)return;state.budget-=cost;r.lanes++;r.flash=1;tone(620,.12);toast(`${r.name} widened to ${r.lanes} lanes`);updateHUD()}
function pause(){if(state.ended)return;state.paused=!state.paused;$('pauseButton').setAttribute('aria-label',state.paused?'Resume game':'Pause game');$('pauseIcon').innerHTML=state.paused?'<path d="m9 6 9 6-9 6V6Z"/>':'<path d="M8 6v12M16 6v12"/>';toast(state.paused?'Simulation paused':'Traffic moving')}
function finish(){state.ended=true;const won=state.averageTime<18;$('resultIcon').textContent=won?'✓':'!';$('resultIcon').style.background=won?C.mint:C.coral;$('resultEyebrow').textContent=won?'CITY MOVING':'GRIDLOCK ALERT';$('resultTitle').textContent=won?'Beautifully balanced.':'The city slowed down.';$('resultText').textContent=won?'You kept the town moving while demand climbed.':'Try widening the busiest shortcuts before their queues spread.';$('resultTrips').textContent=state.completed;$('resultTime').textContent=`${state.averageTime.toFixed(1)}m`;$('resultFlow').textContent=`${Math.round(state.networkFlow)}%`;setTimeout(()=>$('endScreen').hidden=false,500);tone(won?740:180,.3)}
function restart(){roads.forEach((r,i)=>{r.lanes=1;r.traffic=0;r.selected=i===2;r.flash=0});Object.assign(state,{elapsed:0,spawnClock:0,paused:false,ended:false,selected:2,cars:[],completed:0,budget:720,averageTime:12.4,networkFlow:100,history:[12.4],nextSample:0,lastFrame:performance.now()});$('endScreen').hidden=true;$('pauseIcon').innerHTML='<path d="M8 6v12M16 6v12"/>';updateHUD()}
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();select(e.clientX-r.left,e.clientY-r.top)});$('upgradeButton').addEventListener('click',upgrade);$('pauseButton').addEventListener('click',pause);$('restartButton').addEventListener('click',restart);$('soundButton').addEventListener('click',()=>{state.sound=!state.sound;$('soundButton').setAttribute('aria-pressed',String(state.sound));if(state.sound)tone(520,.05)});window.addEventListener('resize',()=>{resize();render();drawSpark()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!state.ended&&!state.paused)pause()});
function loop(now){const dt=Math.min(.05,(now-state.lastFrame)/1000);state.lastFrame=now;update(dt);render();updateHUD();requestAnimationFrame(loop)}resize();updateHUD();requestAnimationFrame(loop);
})();
